baseURL: https://yanirseroussi.com/
copyright: '&copy; [Yanir Seroussi](https://yanirseroussi.com/about/)&nbsp;&nbsp;|'
enableGitInfo: true
languageCode: en-au
theme: papermod
title: Yanir Seroussi | Data science and beyond

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Talks
      url: /talks/
      weight: 2
    - name: FAQ
      url: /faq/
      weight: 3

params:
  analytics:
    google:
      siteVerificationTag: aWlue7NGcj4dQpjOKJF7YKiAvw3JuHnq6aFqX6VwWAU
  comments: true
  cover:
    hidden: false
  disableScrollToTop: true
  editPost:
    appendFilePath: true
    text: Suggest changes
    url: https://github.com/yanirs/yanirseroussi.com/blob/master/content
  homeInfoParams:
    title: '![Yanir Seroussi profile picture](apple-touch-icon.png) Welcome! üê≥Ô∏è'
    content: |
      Check out the [About](/about/) page for a general intro and contact options. Browse recent posts below, and get
      notified about new posts by subscribing to the mailing list at [the bottom of any page](#mailing-list-email) or on
      [TinyLetter](https://tinyletter.com/yanir).
  mainSections: post
  showShareButtons: true

taxonomies:
  tag: tags
