baseURL: https://yanirseroussi.com/
copyright: 'Text and figures licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) by [Yanir Seroussi](https://yanirseroussi.com/about/), except where noted otherwise'
enableGitInfo: true
languageCode: en-au
pagination:
  pagerSize: 10000
theme: papermod
title: Yanir Seroussi â€“ AI/ML Success Architect

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Writing
      url: /posts/
      weight: 2
    - name: Speaking
      url: /talks/
      weight: 3
    - name: Consulting
      url: /consult/
      weight: 4

params:
  analytics:
    google:
      siteVerificationTag: aWlue7NGcj4dQpjOKJF7YKiAvw3JuHnq6aFqX6VwWAU
  author: Yanir Seroussi
  comments: true
  cover:
    hiddenInList: true
  description: |
    Helping climate tech founders ship AI/ML solutions that support multi-million dollar growth goals (hype-free artificial intelligence, machine learning, and data science).
  disableScrollToTop: true
  editPost:
    disabled: true
  hideFooter: true
  profileMode:
    enabled: true
    title: 'Yanir Seroussi<br><a href="/2026/01/26/what-is-an-ai-ml-success-architect/">AI/ML Success Architect</a>'
    subtitle: |
      **Current mission:**
      : [Help climate tech founders ship AI/ML solutions that support multi-million dollar growth goals.](/consult/)

      **Industry experience:**
      : [Over a decade with startups & scaleups across data science, engineering, and tech leadership roles.](/about/)
      
      **Formal education:**
      : [BSc in Computer Science. PhD in Artificial Intelligence. Still learning every day.](/about/#past-work-examples)

      **Sample testimonial:**
      : _["The single most talented person I've had the opportunity to work with in my nearly 15 years in Data/ML."](/about/#testimonials)_

      **Writing topics:**
      : [Data / AI / ML, with a focus on practical applications in industry.](/posts/)
    imageUrl: /home-profile.webp
    imageTitle: Yanir Seroussi's profile picture
    imageWidth: 278
    imageHeight: 250
    buttons:
      - name: About
        url: /about/
      - name: Writing
        url: /posts/
      - name: Speaking
        url: /talks/
      - name: Consulting Services
        url: /consult/
  socialIcons:
    - name: LinkedIn
      url: https://www.linkedin.com/in/yanirseroussi/
    - name: GitHub
      url: https://github.com/yanirs/
    - name: GoogleScholar
      url: https://scholar.google.com.au/citations?user=NR254LoAAAAJ
    - name: Email
      url: /contact/
  mainSections: post
  showRssButtonInSectionTermList: false
  showShareButtons: true

taxonomies:
  tag: tags
